name: Game Build and Deploy 🎮

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions: 
  contents: write
  

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  
  buildAndroid:
    
    name: Build for Android 📱
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard
      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-StandaloneWindows64
          restore-keys: |
            Library-build-
            Library-
      - uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
          buildName: SnakeGame

      - uses: actions/upload-artifact@v2
        with:
          name: SnakeGame
          path: build/Android
          
  deployToBranch:
    needs: buildAndroid
    name: Deploy to Builds branch 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: SnakeGame
          path: SnakeGame
      
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: AndroidBuild
          folder: SnakeGame
          target-folder: SnakeGame
  tag_release:
    needs: deployToBranch
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: AndroidBuild
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          ##  Any commit message that includes #major, #minor, #patch, or #none will trigger the respective version bump
